package smplkit

import "time"

// Config represents a configuration resource from the smplkit platform.
type Config struct {
	// ID is the unique identifier (UUID) of the config.
	ID string
	// Key is the human-readable config key (e.g. "user_service").
	Key string
	// Name is the display name for the config.
	Name string
	// Description is an optional description of the config.
	Description *string
	// Parent is the parent config UUID, or nil for root configs.
	Parent *string
	// Values holds the base configuration values.
	Values map[string]interface{}
	// Environments maps environment names to their value overrides.
	Environments map[string]map[string]interface{}
	// CreatedAt is the creation timestamp.
	CreatedAt *time.Time
	// UpdatedAt is the last-modified timestamp.
	UpdatedAt *time.Time
}

// CreateConfigParams holds the parameters for creating a new config.
type CreateConfigParams struct {
	// Name is the display name (required).
	Name string
	// Key is the human-readable key. Auto-generated by the server if nil.
	Key *string
	// Description is an optional description.
	Description *string
	// Parent is the parent config UUID.
	Parent *string
	// Values holds the initial base values.
	Values map[string]interface{}
}

// GetOption configures a Get request. Use WithKey or WithID to specify
// the lookup strategy.
type GetOption func(*getConfig)

type getConfig struct {
	key *string
	id  *string
}

// WithKey returns a GetOption that looks up a config by its human-readable key.
func WithKey(key string) GetOption {
	return func(g *getConfig) {
		g.key = &key
	}
}

// WithID returns a GetOption that looks up a config by its UUID.
func WithID(id string) GetOption {
	return func(g *getConfig) {
		g.id = &id
	}
}

// --- JSON:API serialization structs (unexported) ---

// jsonAPIRequest is the JSON:API envelope for create/update requests.
type jsonAPIRequest struct {
	Data jsonAPIResourceRequest `json:"data"`
}

// jsonAPIResourceRequest is a single JSON:API resource in a request.
type jsonAPIResourceRequest struct {
	Type       string                 `json:"type"`
	Attributes jsonAPIConfigAttrsReq  `json:"attributes"`
}

// jsonAPIConfigAttrsReq holds the config attributes for a create/update request.
type jsonAPIConfigAttrsReq struct {
	Name        string                 `json:"name"`
	Key         *string                `json:"key,omitempty"`
	Description *string                `json:"description,omitempty"`
	Parent      *string                `json:"parent,omitempty"`
	Values      map[string]interface{} `json:"values,omitempty"`
}

// jsonAPISingleResponse is the JSON:API envelope for a single-resource response.
type jsonAPISingleResponse struct {
	Data jsonAPIResource `json:"data"`
}

// jsonAPIListResponse is the JSON:API envelope for a list response.
type jsonAPIListResponse struct {
	Data []jsonAPIResource `json:"data"`
}

// jsonAPIResource is a single JSON:API resource in a response.
type jsonAPIResource struct {
	ID         string              `json:"id"`
	Type       string              `json:"type"`
	Attributes jsonAPIConfigAttrs  `json:"attributes"`
}

// jsonAPIConfigAttrs holds the config attributes from a JSON:API response.
type jsonAPIConfigAttrs struct {
	Name         string                            `json:"name"`
	Key          string                            `json:"key"`
	Description  *string                           `json:"description"`
	Parent       *string                           `json:"parent"`
	Values       map[string]interface{}             `json:"values"`
	Environments map[string]map[string]interface{}  `json:"environments"`
	CreatedAt    *time.Time                         `json:"created_at"`
	UpdatedAt    *time.Time                         `json:"updated_at"`
}

// toConfig converts a JSON:API resource into a public Config.
func (r *jsonAPIResource) toConfig() *Config {
	return &Config{
		ID:           r.ID,
		Key:          r.Attributes.Key,
		Name:         r.Attributes.Name,
		Description:  r.Attributes.Description,
		Parent:       r.Attributes.Parent,
		Values:       r.Attributes.Values,
		Environments: r.Attributes.Environments,
		CreatedAt:    r.Attributes.CreatedAt,
		UpdatedAt:    r.Attributes.UpdatedAt,
	}
}
